baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Maxime Lalisse'

theme = "cactus"

[params]
  colortheme = "white" # dark, light, white, or classic
  description = "o/"

[[menu.main]]
name = "Email"
url = "mailto:maxime@lalis.se"
weight = 1

[[menu.main]]
name = "Github"
url = "https://github.com/mjal"
weight = 2

[[deployment.targets]]
  URL = "s3://bucket?endpoint=garage.deuxfleurs.fr&s3ForcePathStyle=true&region=garage"
