baseURL = 'https://maxime.lalis.se/'
languageCode = 'en-us'
title = 'Maxime Lalisse'

theme = "cactus"

[params]
  colortheme = "white" # dark, light, white, or classic

[[menu.main]]
name = "Email"
url = "mailto:maxime@lalis.se"
weight = 1

[[menu.main]]
name = "Github"
url = "https://github.com/mjal"
weight = 2

[[menu.main]]
name = "CV"
url = "/cv.pdf"
weight = 3

[[deployment.targets]]
  URL = "s3://bucket?endpoint=garage.deuxfleurs.fr&s3ForcePathStyle=true&region=garage"
