baseURL = 'https://maxime.lalis.se/'
languageCode = 'en-us'
title = 'Maxime Lalisse'

theme = "cactus"

[params]
  colortheme = "white" # dark, light, white, or classic
  mainSection = "posts"
  mainSectionTitle = "Blog"
  showAllPostsOnHomePage = true
  #description = "My main interests are online privacy and e-voting."

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 1

[[menu.main]]
name = "Email"
url = "mailto:maxime@lalis.se"
weight = 2

[[menu.main]]
name = "Github"
url = "https://github.com/mjal"
weight = 3

[[menu.main]]
name = "cv"
url = "/cv.pdf"
weight = 4

[[deployment.targets]]
  URL = "s3://bucket?endpoint=garage.deuxfleurs.fr&s3ForcePathStyle=true&region=garage"
